version: "3.8"

services:
  db:
    image: postgres:14
    container_name: user_db_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: users_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"

  product-db:
    image: mongo:5.0
    container_name: product_db_container
    environment:
      MONGO_INITDB_DATABASE: products_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  user-service:
    build: ./user-service
    container_name: user_service_container
    environment:
      # PostgreSQL
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASS: mypassword
      DB_NAME: users_db
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TTL: 300               
    depends_on:
      - db
      - redis
    ports:
      - "8001:8001"
    volumes:
    - ./user-service:/app

  product-service:
    build: ./product-service
    container_name: product_service_container
    environment:
      # MongoDB
      MONGO_HOST: product-db
      MONGO_PORT: 27017
      MONGO_DB: products_db
    depends_on:
      - product-db
    ports:
      - "8002:8002"

  cart-service:
    build: ./cart-service
    container_name: cart_service_container
    depends_on:
      - user-service  
      - product-service
    ports:
      - "8003:8003"

volumes:
  postgres_data:
  mongo_data:
