version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "8001:8001"

  product-service:
    build: ./product-service
    ports:
      - "8002:8002"

  cart-service:
    build: ./cart-service
    ports:
      - "8003:8003"