version: '3.8'

services:
  db:
    image: postgres:14
    container_name: user_db_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  product-db:
    image: mongo:5.0
    container_name: product_db_container
    environment:
      MONGO_INITDB_DATABASE: products_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user-service:
    build: ./user-service
    container_name: user_service_container
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASS: mypassword
      DB_NAME: users_db
    ports:
      - "8001:8001"
    depends_on:
      - db

  product-service:
    build: ./product-service
    container_name: product_service_container
    environment:
      MONGO_HOST: product-db
      MONGO_PORT: 27017
      MONGO_DB: products_db
    ports:
      - "8002:8002"
    depends_on:
      - product-db
      
  cart-service:
    build: ./cart-service
    container_name: cart_service_container
    ports:
      - "8003:8003"
    depends_on:
      - user-service

volumes:
  postgres_data:
  mongo_data:
